// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zayummhdllwamoevewoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpheXVtbWhkbGx3YW1vZXZld29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Mjg2ODQsImV4cCI6MjA2NTEwNDY4NH0.MTNw98eGZHFZLMPBwvWwciOJ0hpgjLt_4wztKCjucKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);